#!/bin/sh
#
# $NetBSD: kbdmap,v 1.9 2004/08/13 18:08:03 mycroft Exp $
#

# PROVIDE: kbdmap
# BEFORE:  LOGIN

$_rc_subr_loaded . /etc/rc.subr

name="kbdmap"
start_cmd="kbdmap_start"
stop_cmd=":"

kbdmap_start()
{
	echo "Updating kbdmap."
	[ -z $kbdmap ] || loadkmap < /usr/share/kmap/${kbdmap}.kmap
}

load_rc_config $name
run_rc_command "$1"
