#!/bin/sh
#
# $NetBSD: klogd,v 1.15 2004/10/11 13:29:52 lukem Exp $
#

# PROVIDE: klogd
# REQUIRE: syslogd
# BEFORE:  SERVERS sysctl

$_rc_subr_loaded . /etc/rc.subr

name="klogd"
rcvar=$name
command="/sbin/${name}"
pidfile="/var/run/${name}.pid"
extra_commands="reload"

load_rc_config $name
run_rc_command "$1"
