#!/bin/sh
#
# Copyright (c) 2015 Red Cool Beans
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# Author: Robert Nagy <robert@redcoolbeans.com>


PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

export TERM=xterm-color

usage() {
	echo
	echo "Usage: ${0##*/} [-cfnu]" >&2
	echo
	echo "Options:"
	echo "  -c    check if the base system needs upgrading with -u"
	echo "  -f    force installation to the disk(s)"
	echo "  -n    dry-run mode, only report what would be done"
	echo "  -u    run upgrade steps required for the current release"
	echo
	exit 1
}

pr_error() {
	echo "!!! ${@}"
	exit 1
}

if [ "$(id -u)" -ne 0 ]; then
	pr_error "Need root privileges to run this script"
	usage
fi

_TMPDIR=$(mktemp -d) || exit 1
_PID="/var/run/${0##*/}.pid"
# Based on the machine type, lookup the associated CargOS platform name.
# XXX: This currently assumes all ARMv7s are rpi2 which is easier for
# the time being, but will not hold true when other boards are added.
_arch=$(uname -m | sed -e 's/armv7l/rpi2/')

trap "bye_bye" 0 1 2 5 15

bye_bye() {
	umount -f /boot 2>/dev/null
	rm -rf ${_TMPDIR} ${_PID}
	exit 1
}

cmd_exe() {
	if [ -z "${dryrun}" ]; then
		"${@}"
	fi
}

# CargOS upgrade 2015.9 -> 2015.10
upgrade_20159_to_201510() {
	upgrade_20157_to_20158
}

# CargOS upgrade 2015.8 -> 2015.9
upgrade_20158_to_20159() {
	upgrade_20157_to_20158
}

# CargOS upgrade 2015.7 -> 2015.8
upgrade_20157_to_20158() {
	clear
	PKG_PATH=http://download.cargos.io/$(cat /etc/cargos-release)/$(uname -m)/packages/All
	/usr/pkg/bin/pkgin -y up && /usr/pkg/bin/pkgin -y fug
	rm -rf /usr/pkg/var/chroot/sshd && mkdir -p /usr/pkg/var/chroot/sshd
	/usr/pkg/sbin/pkg_delete -f openssl
	for p in $(/usr/pkg/sbin/pkg_info | cut -d ' ' -f1 | sed 's/.[^-]*$//')
	do
		PKG_PATH=${PKG_PATH} /usr/pkg/sbin/pkg_add -U $p
	done
	source /etc/profile && /usr/pkg/bin/pkgin -y up && /usr/pkg/bin/pkgin -y fug && \
		/usr/pkg/bin/pkgin -f up
	/bin/sync
	_message="
	The upgrade requires a reboot. Do you want to reboot now?
	"
	dialog --backtitle "${TITLE_PREFIX}" \
		--title "CargOS Upgrade Utility" \
		--yesno "${_message}" 7 80
	[ $? -gt 0 ] && exit 0
	/sbin/reboot
}

cargos_check_upgrade() {
	. /etc/os-release
	_cver=$(cat /etc/cargos-release)
	[ X"${VERSION}" != X"${_cver}" ] && \
		[ X"$(type -t upgrade_${VERSION//./}_to_${_cver//./})" == X"function" ] && \
			echo "Your CargOS installation needs to be updated with 'cargos-upgrade -u' !"
	exit 0
}

cargos_upgrade() {
	. /etc/os-release
	_cver=$(cat /etc/cargos-release)
	if [ X"${VERSION}" == X"${_cver}" ]; then
		_message="
		Your CargOS installation on the disk(s) is up-to-date!
		"
		dialog --backtitle "${TITLE_PREFIX}" \
			--title "CargOS Upgrade Utility" \
			--msgbox "${_message}" 7 60
		clear && exit 0
	fi
	_message="
	Do you want to proceed with the upgrade from ${VERSION} to ${_cver} ?
	"
	dialog --backtitle "${TITLE_PREFIX}" \
		--title "CargOS Upgrade Utility" \
		--yesno "${_message}" 7 70
	[ $? -gt 0 ] && exit 0
	echo -n "* Executing upgrade_${VERSION//./}_to_${_cver//./} ... "
	cmd_exe upgrade_${VERSION//./}_to_${_cver//./}
	[ $? -eq 0 ] && echo 'done.' || pr_error 'FAILED'
	exit 0
}

while getopts 'cfnu' arg; do
	case ${arg} in
	c)	check=1 ;;
	n)	dryrun=" (dry run)" ;;
	f)	force=1 ;;
	u)	upgrade=1 ;;
	*)	usage ;;
	esac
done
[ $# = $(($OPTIND-1)) ] || usage

if [ -f ${_PID} ]; then
	pr_error "${0##*/} is already running ($(cat ${_PID})):"
fi

echo $$ >${_PID}

[ -z ${check} ] || cargos_check_upgrade
[ -z ${upgrade} ] || cargos_upgrade

_wget=$(which wget) || _wget="/usr/pkg/bin/wget"
_grub_install=$(which grub-install) || _grub_install="/usr/pkg/sbin/grub-install"

if [ ! -e ${_wget} ]; then
	pr_error "${0##*/} needs wget to be installed, please issue 'pkgin in wget' to install."
fi

if [ ! -e ${_grub_install} ]; then
	pr_error "${0##*/} needs grub2 to be installed: please issue 'pkgin in grub2' to install."
fi

_rver=$(${_wget} -qO - http://download.cargos.io/current)
_cver=$(cat /etc/cargos-release)

if [ X"${_rver}" == X"${_cver}" ]; then
	_message="
	Your CargOS installation on the disk(s) is up-to-date!
	"
	dialog --backtitle "${TITLE_PREFIX}" \
		--title "CargOS Upgrade Utility" \
		--msgbox "${_message}" 7 60
	clear && exit 0
else
	_message="
	Do you want to proceed with the upgrade?!
	"
	dialog --backtitle "${TITLE_PREFIX}" \
		--title "CargOS Upgrade Utility" \
		--yesno "${_message}" 7 60
	[ $? -gt 0 ] && exit 0
fi

clear

cmd_exe cat << EOF > /tmp/grub.cfg
set menu_color_normal=cyan/blue
set menu_color_highlight=white/blue
set timeout=10

menuentry 'CargOS-${_rver}' {
    set background_color=black
    linux    /bzImage-${_rver} root=/dev/ram0 ramdisk_size=131072 quiet
    initrd   /rootfs.squashfs-noinst-${_rver}
}
menuentry 'CargOS-${_cver}' {
    set background_color=black
    linux    /bzImage-${_cver} root=/dev/ram0 ramdisk_size=131072 quiet
    initrd   /rootfs.squashfs-noinst-${_cver}
}
menuentry 'CargOS-${_rver} with serial console on ttyS0' {
    set background_color=black
    linux    /bzImage-${_rver} console=ttyS0 root=/dev/ram0 ramdisk_size=131072 quiet
    initrd   /rootfs.squashfs-noinst-${_rver}
}
menuentry 'CargOS-${_cver} with serial console on ttyS0' {
    set background_color=black
    linux    /bzImage-${_cver} console=ttyS0 root=/dev/ram0 ramdisk_size=131072 quiet
    initrd   /rootfs.squashfs-noinst-${_cver}
}
EOF

for _version in ${_rver} ${_cver}; do
	echo
	echo -n "* Downloading root filesystem for ${_version} ... "
	cmd_exe /usr/pkg/bin/wget -T5 -t5 -qO /tmp/rootfs.squashfs-noinst-${_version} \
		http://download.cargos.io/${_version}/${_arch}/rootfs.squashfs-noinst-${_version}
	[ $? -eq 0 ] && echo 'done.' || pr_error 'FAILED'
	echo
	echo -n "* Downloading kernel image for ${_version} ... "
	cmd_exe /usr/pkg/bin/wget -T5 -t5 -qO /tmp/bzImage-${_version} \
		http://download.cargos.io/${_version}/${_arch}/bzImage-${_version}
	[ $? -eq 0 ] && echo 'done.' || pr_error 'FAILED'
done

for i in $(pvs --noheadings | awk '{print $1}'); do
	_disk=$(echo $i | tr -d '[[:digit:]]')
	echo
	echo -n "* Running filesystem check on ${_disk}1... "
	cmd_exe fsck.ext4 -p ${_disk}1 >/dev/null
	[ $? -eq 0 ] && echo 'done.' || pr_error 'FAILED'
	cmd_exe mount -t ext4 ${_disk}1 /boot
	[ -z "${dryrun}" ] && [ -z "${force}" ] && if [ ! -e /boot/grub/grub2.cfg ]; then
		cmd_exe umount /boot
		dialog --backtitle "${TITLE_PREFIX}" \
			--title "CargOS Upgrade Utility" \
			--msgbox "
				CargOS is not configured to boot from disk(s)." 7 60
		clear && exit 1
	fi
	echo
	echo -n "* Installing grub boot loader to ${_disk} ... "
	cmd_exe /usr/pkg/sbin/grub-install -f ${_disk} 2>/dev/null
	[ $? -eq 0 ] && echo 'done.' || pr_error 'FAILED'
	cmd_exe cp /tmp/grub.cfg /boot/grub/grub.cfg
	for _version in ${_rver} ${_cver}; do
		echo
		echo -n "* Installing root filesystem for ${_version} to ${_disk} ... "
		cmd_exe cp /tmp/rootfs.squashfs-noinst-${_version} /boot/
		[ $? -eq 0 ] && echo 'done.' || pr_error 'FAILED'
		echo
		echo -n "* Installing kernel for ${_version} to ${_disk} ... "
		cmd_exe cp /tmp/bzImage-${_version} /boot/
		[ $? -eq 0 ] && echo 'done.' || pr_error 'FAILED'
	done

	# clean up old rootfs and kernel files
	[ -z "${dryrun}" ] && find /boot ! -name "*${_cver}*" -a ! -name "*${_rver}*" -maxdepth 1 -type f -exec rm {} \;
	cmd_exe umount /boot
done

cmd_exe rm -f /tmp/bzImage-${_cver} /tmp/rootfs.squashfs-noinst-${_cver} /tmp/grub.cfg

rm -rf ${_TMPDIR}
rm ${_PID}
